### ISSUE TITLE
Cost

### ISSUE THREAD

**Issue by mirik12** [den-vasyliev/tf-google-gke-cluster#3]
Project: mirik12/tf-google-gke-cluster

 Name                                                 Monthly Qty  Unit   Monthly Cost 
                                                                                       
 google_container_cluster.this                                                         
 └─ Cluster management fee                                    730  hours        $73.00 
                                                                                       
 google_container_node_pool.this                                                       
 ├─ Instance usage (Linux/UNIX, on-demand, g1-small)        1,460  hours        $26.27 
 └─ Standard provisioned storage (pd-standard)                200  GB            $8.00 
                                                                                       
 OVERALL TOTAL                                                                 $107.27 
──────────────────────────────────
2 cloud resources were detected:
∙ 2 were estimated, all of which include usage-based costs, see https://infracost.io/usage-file

**Comment by den-vasyliev** [comment]
PR preferred
